### ISSUE TITLE
What's the function about the variable 'self.g' in lsqplus_quantiza_V1.py

### ISSUE THREAD

**Issue by huanmei9** [ZouJiu1/LSQplus#2]
Thanks for your open source work. There is an initalization variable `self.g` in _lsqqlus_quantiza_V1.py:L138_, I'm wondering the usage of it. 
Looking forward to your reply.

**Comment by ZouJiu1** [comment]
It's used to keep the gradient update rating of self.s and self.b, if you drop this parameter, you will find that the update of self.s and self.b become unstable. Self.g keep the update rating same as NN'weight. So it is necessary for convergence.
