### ISSUE TITLE
Question about your code

### ISSUE THREAD

**Issue by huanmei9** [ZouJiu1/LSQplus#3]
I'm wondering if there are some mistakes in [this code](https://github.com/ZouJiu1/LSQplus/blob/44695a87c2ca5c7b31606dda788b1d3ead30ae1a/quantization/lsqplus_quantize_V1.py#L213). This function is to get the inital value about Scalebeta of activation_quantizer. Why need to get the gradiant about weight, and use it to update activation_quantizer's parameters. Is it more appropriate to change to `weight = child.input` ?
Looking forward to your reply.

**Comment by ZouJiu1** [comment]
I will check
