### ISSUE TITLE
LSQplus 论文初始化方法实现的疑问

### ISSUE THREAD

**Issue by TaooCAI** [ZouJiu1/LSQplus#8]
```Python
def update_LSQplus_activation_Scalebeta(model):
    for name, child in model.named_children():
        if isinstance(child, (QuantConv2d, QuantConvTranspose2d, QuantLinear)):
            weight = child.weight.data
            s = child.activation_quantizer.s.data
            beta = child.activation_quantizer.beta.data
            Qn = child.activation_quantizer.Qn
            Qp = child.activation_quantizer.Qp
            g = child.activation_quantizer.g
            # print('before: ', name, child.activation_quantizer.s.grad.data, child.activation_quantizer.beta.grad.data, s, beta)
            q_w = (weight - beta) / s
            # print(q_w)
            smaller = (q_w < Qn).float() #bool值转浮点值，1.0或者0.0
            bigger = (q_w > Qp).float() #bool值转浮点值，1.0或者0.0
            between = 1.0 - smaller -bigger #得到位于量化区间的index
            grad_alpha = ((smaller * Qn + bigger * Qp + 
                           between * Round.apply(q_w) - between * q_w) * g).sum().unsqueeze(dim=0)
            grad_beta = ((smaller + bigger) * g).sum().unsqueeze(dim=0)
            # print('grad_beta: ',grad_beta,g, smaller.sum(), bigger.sum(), between.sum(),Qn, Qp)
            child.activation_quantizer.s.grad.data.add_(g*(2*(child.quant_input-child.input)*grad_alpha).sum().unsqueeze(dim=0))
            child.activation_quantizer.beta.grad.data.add_(g*(2*(child.quant_input-child.input)*grad_beta).sum().unsqueeze(dim=0))
```
- [lsqplus_quantize_V1.py#L213](https://github.com/ZouJiu1/LSQplus/blob/master/quantization/lsqplus_quantize_V1.py#L213)
- 为什么 grad_alpha 求的是 conv weight 关于 s 的导数，而不是 quant_input 关于 s 的导数？是我哪里理解错了，还是这里有个 bug ?

**Comment by ZouJiu1** [comment]
I fix it, you can try it again, [https://github.com/ZouJiu1/LSQplus/commit/828e6846d5355a91372a08cb33ddfd7abe832b10](https://github.com/ZouJiu1/LSQplus/commit/828e6846d5355a91372a08cb33ddfd7abe832b10)

**Comment by ZouJiu1** [comment]
these two lines, g can be removed or keeped, it will balance or slow down the learning_rate of those params. [https://github.com/ZouJiu1/LSQplus/blob/master/quantization/lsqplus_quantize_V1.py#L229-L230](https://github.com/ZouJiu1/LSQplus/blob/master/quantization/lsqplus_quantize_V1.py#L229-L230)

**Comment by brisker** [comment]
@ZouJiu1 @TaooCAI 
二位好， 请教下为什么量化间隔的梯度计算， 需要有这个变量：
![image](https://github.com/ZouJiu1/LSQplus/assets/13804492/8ac24ce4-5640-437c-96d0-d391efc6635a)
![image](https://github.com/ZouJiu1/LSQplus/assets/13804492/6249055a-fcc8-47c0-a30c-ec0774fbc62b)

**Comment by brisker** [comment]
@ZouJiu1 @TaooCAI 
二位好， 请教下为什么量化间隔的梯度计算， 需要有这个变量：
![image](https://github.com/ZouJiu1/LSQplus/assets/13804492/8ac24ce4-5640-437c-96d0-d391efc6635a)
![image](https://github.com/ZouJiu1/LSQplus/assets/13804492/6249055a-fcc8-47c0-a30c-ec0774fbc62b)
